/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Clases.Caja;
import Clases.Concepto;
import Clases.Maestro;
import Clases.Operario;
import Clases.Remiseria;
import Clases.Utilidad;
import java.awt.Color;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author garba
 */
public class JDialogConceptos extends javax.swing.JDialog {
    private Remiseria remiseria;
    private Caja unaCaja;
    private Maestro unMaestro;
    private Operario unOperario;
    private Utilidad utilidades;
    private String tipo;
    private JComboBox comboEntrada;
    private JComboBox comboSalida;
    /**
     * Creates new form JDialogConceptos
     */
    public JDialogConceptos(java.awt.Frame parent, boolean modal,Remiseria remiseria, Maestro unMaestro, Operario unOperario, Utilidad utilidades, String tipo, JComboBox comboEntrada, JComboBox comboSalida){
        super(parent, modal);
        this.utilidades = utilidades;
        this.remiseria =remiseria;
        this.unaCaja = remiseria.getCajaPrincipal();  
        this.unMaestro = unMaestro;
        this.unOperario = unOperario;
        this.tipo = tipo;
        this.comboEntrada = comboEntrada;
        this.comboSalida = comboSalida;
        initComponents();
        if(tipo.equals("Entrada"))
        {
            cbx_tipoConcepto.setSelectedIndex(1);
        }
        else if(tipo.equals("Salida"))
        {
            cbx_tipoConcepto.setSelectedIndex(2);
        }
        this.tbl_conceptos.getColumn("Tipo").setMaxWidth(100);
        this.setModal(true);
        this.setLocationRelativeTo(null);
        cargarCampos();
    }

    private void cargarCampos() {
        cbx_tipoConceptoItemStateChanged(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_addConcepto = new javax.swing.JButton();
        btn_delConcepto = new javax.swing.JButton();
        btn_modConcepto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Scroll_tblConceptos = new javax.swing.JScrollPane();
        tbl_conceptos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_detalleConcepto = new javax.swing.JTextField();
        lbl_resultado = new javax.swing.JLabel();
        cbx_tipoConcepto = new javax.swing.JComboBox();
        jPanel29 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_addConcepto.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btn_addConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/package-install (2).png"))); // NOI18N
        btn_addConcepto.setText("Agregar");
        btn_addConcepto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_addConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addConceptoActionPerformed(evt);
            }
        });

        btn_delConcepto.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btn_delConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-trash.png"))); // NOI18N
        btn_delConcepto.setText("Eliminar");
        btn_delConcepto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_delConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_delConceptoMouseClicked(evt);
            }
        });
        btn_delConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delConceptoActionPerformed(evt);
            }
        });

        btn_modConcepto.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btn_modConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/leafpad.png"))); // NOI18N
        btn_modConcepto.setText("Modificar");
        btn_modConcepto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_modConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modConceptoActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application-exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_addConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btn_delConcepto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modConcepto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_addConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(117, 150, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Scroll_tblConceptos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Scroll_tblConceptos.setAutoscrolls(true);
        Scroll_tblConceptos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Scroll_tblConceptosMouseClicked(evt);
            }
        });

        tbl_conceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Detalle del Concepto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_conceptos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_conceptosMouseClicked(evt);
            }
        });
        tbl_conceptos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbl_conceptosKeyTyped(evt);
            }
        });
        Scroll_tblConceptos.setViewportView(tbl_conceptos);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabel5.setText("Tipo:");

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabel6.setText("Detalle");

        txt_detalleConcepto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_detalleConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_detalleConceptoMouseClicked(evt);
            }
        });

        lbl_resultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cbx_tipoConcepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Entrada", "Salida" }));
        cbx_tipoConcepto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_tipoConceptoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_tipoConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_detalleConcepto)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_detalleConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tipoConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Scroll_tblConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Scroll_tblConceptos, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel30.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel30.setText("Gestor de Conceptos");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_conceptosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_conceptosMouseClicked
        txt_detalleConcepto.setText(tbl_conceptos.getValueAt(tbl_conceptos.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tbl_conceptosMouseClicked

    private void tbl_conceptosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_conceptosKeyTyped

    }//GEN-LAST:event_tbl_conceptosKeyTyped

    private void Scroll_tblConceptosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Scroll_tblConceptosMouseClicked

    }//GEN-LAST:event_Scroll_tblConceptosMouseClicked
  public void cargarEntrada()
  {
      comboEntrada.removeAllItems();
      Collection conceptoEntrada = unaCaja.getConceptos().values();
      if(conceptoEntrada != null)
      {
        Concepto con = null;
        Iterator iter = conceptoEntrada.iterator();
        while(iter.hasNext())
        {
            con = (Concepto) iter.next();
            if(con.getTipo().equals("Entrada"))
            {
                comboEntrada.addItem(con.toString());
            }
        }
      }
  
  }
    public void cargarSalida()
  {
      comboSalida.removeAllItems();
      Collection conceptoSalida = unaCaja.getConceptos().values();
        if(conceptoSalida != null)
        {
        Concepto con = null;
        Iterator iter = conceptoSalida.iterator();
        while(iter.hasNext())
        {
            con = (Concepto) iter.next();
            if(con.getTipo().equals("Salida"))
            {
                comboSalida.addItem(con.toString());
            }
        }
      }
  
  } 
    
    private void btn_addConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addConceptoActionPerformed
        if(!txt_detalleConcepto.getText().isEmpty())
        {
            String tipoConcepto = cbx_tipoConcepto.getSelectedItem().toString();
            String detalleConcepto = txt_detalleConcepto.getText();
            List<Concepto> lista = new LinkedList<>();

            try {

                Concepto nuevoConceptos = unaCaja.agregarConcepto(tipoConcepto, detalleConcepto);
                //remiseria.crearAuditoria("ADD", "Agregó el Concepto " + detalleConcepto + " de tipo " + tipoConcepto, Acceso.getUsuario(), GUIM.getHoraActual());

                lbl_resultado.setText("El concepto: " + detalleConcepto + " se ha cargado correctamente");
                //            GUIM.cargarTablaConceptos(tbl_conceptos, unaCaja.getConceptos());
                if (nuevoConceptos.getTipo().equals("Entrada")) {
                    cbx_tipoConcepto.setSelectedIndex(1);
                    this.cargarEntrada();
                    Collection conceptos = remiseria.getCajaPrincipal().getConceptos().values();
                    Concepto conc = null;

                    Iterator iter = conceptos.iterator();
                    while(iter.hasNext())
                    {
                        conc = (Concepto) iter.next();
                        if(conc.getTipo().equals("Entrada"))
                        {
                            lista.add(conc);
                        }
                    }
                     this.cargarTablaConceptos(tbl_conceptos,lista );                
                    cbx_tipoConceptoItemStateChanged(null);
                } else {
                    cbx_tipoConcepto.setSelectedIndex(2);
                    this.cargarSalida();
                    Collection conceptos = remiseria.getCajaPrincipal().getConceptos().values();
                    Concepto conc = null;
                   // List<Concepto> lista = new LinkedList<>();
                    Iterator iter = conceptos.iterator();
                    while(iter.hasNext())
                    {
                        conc = (Concepto) iter.next();
                        if(conc.getTipo().equals("Salida"))
                        {
                            lista.add(conc);
                        }
                    }
                    this.cargarTablaConceptos(tbl_conceptos,lista );                
                    cbx_tipoConceptoItemStateChanged(null);
                }
                txt_detalleConcepto.setText("");
                if(lista!= null)
                {
                    this.cargarTablaConceptos(tbl_conceptos,lista );       
                }
            } catch (Exception ex) {
                lbl_resultado.setText(ex.getMessage());
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"No ha ingresado el nombre del Concepto", null, JOptionPane.ERROR_MESSAGE);
            txt_detalleConcepto.setBackground(Color.red);
        }
    }//GEN-LAST:event_btn_addConceptoActionPerformed

    private void btn_delConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delConceptoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_delConceptoMouseClicked
    public static void limpiar_tabla(JTable tabla) {
        int filas = tabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    
    public static void cargarTablaConceptos(JTable tabla, List<Concepto> unaLista) {
        limpiar_tabla(tabla);
        for (Concepto unConcepto : unaLista) {
            ((DefaultTableModel) tabla.getModel()).addRow(unConcepto.toVector());
        }
    }
    private void btn_delConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delConceptoActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar el Concepto seleccionado?","Advertencia", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            try {
                Concepto unConcepto = (Concepto) tbl_conceptos.getValueAt(tbl_conceptos.getSelectedRow(), 1);
                unaCaja.eliminarConcepto(unConcepto);
                if(unMaestro != null)
                {               
                   remiseria.crearAuditoria("DEL", "class Clases.Concepto" , unMaestro.toString() ,utilidades.getHoraActual());
                }
                else
                {
                    remiseria.crearAuditoria("DEL", "class Clases.Concepto" , unMaestro.toString() ,utilidades.getHoraActual());
                }
                txt_detalleConcepto.setText("");
                List lista = new LinkedList();
                Collection col =  remiseria.getCajaPrincipal().getConceptos().values();
                Concepto c = null;
                Iterator iter = col.iterator();
                while(iter.hasNext())
                {
                    c = (Concepto) iter.next();
                    lista.add(c);
                }
                this.cargarTablaConceptos(tbl_conceptos, lista);
                this.cargarEntrada();
                this.cargarSalida();
            } catch (Exception e) {
                lbl_resultado.setText(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_delConceptoActionPerformed

    private void btn_modConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modConceptoActionPerformed
        if (txt_detalleConcepto.getText() != null) {
            try {
                Concepto unConcepto = (Concepto) tbl_conceptos.getValueAt(tbl_conceptos.getSelectedRow(), 1);
                String detalleConcepto = unConcepto.getDetalle();
                String tipoConcepto = unConcepto.getTipo();
                unaCaja.modificarConcepto(unConcepto, tipoConcepto, txt_detalleConcepto.getText());
                if(unMaestro != null)
                {
                  //  remiseria.crearAuditoria("MOD", "Modificó el Concepto " + detalleConcepto + " (" + tipoConcepto + ") a" + txt_detalleConcepto.getText(),unMaestro.getNombre()+" "+ unMaestro.getApellido(), utilidades.getHoraActual());
                }
                else
                {
                   // remiseria.crearAuditoria("MOD", "Modificó el Concepto " + detalleConcepto + " (" + tipoConcepto + ") a" + txt_detalleConcepto.getText(), unOperario.getNombre()+" "+ unOperario.getApellido(), utilidades.getHoraActual());
                }
                List<Concepto> lista = new LinkedList<>();
                Collection col =  remiseria.getCajaPrincipal().getConceptos().values();
                Iterator iter = col.iterator();
                while(iter.hasNext())
                {
                    lista.add((Concepto)(iter.next()));
                }
                this.cargarEntrada();
                this.cargarSalida();
                this.cargarTablaConceptos(tbl_conceptos, lista);
                txt_detalleConcepto.setText("");
            } catch (Exception ex) {
                lbl_resultado.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_modConceptoActionPerformed

    private void cbx_tipoConceptoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_tipoConceptoItemStateChanged
        String unTipo = cbx_tipoConcepto.getSelectedItem().toString();

        List<Concepto> ingresos = new LinkedList<>();
        List<Concepto> egresos = new LinkedList<>();
        for (Concepto unC : remiseria.getCajaPrincipal().getConceptos().values()) {
            if (unC.getTipo().equals("Entrada")) {
                ingresos.add(unC);
            } else {
                egresos.add(unC);
            }
        }

        if (unTipo.equals("Entrada")) {
            this.cargarTablaConceptos(tbl_conceptos, ingresos);
        } else if (unTipo.equals("Salida")) {
            this.cargarTablaConceptos(tbl_conceptos, egresos);
        } else {
            List lista = new LinkedList();
            Collection col =  remiseria.getCajaPrincipal().getConceptos().values();
            Iterator iter = col.iterator();
            while(iter.hasNext())
            {
                lista.add((Concepto)(iter.next()));
            }
            this.cargarTablaConceptos(tbl_conceptos, lista);
        }
    }//GEN-LAST:event_cbx_tipoConceptoItemStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txt_detalleConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_detalleConceptoMouseClicked
        // TODO add your handling code here:
        txt_detalleConcepto.setBackground(Color.white);
    }//GEN-LAST:event_txt_detalleConceptoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogConceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogConceptos dialog = new JDialogConceptos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll_tblConceptos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btn_addConcepto;
    private javax.swing.JButton btn_delConcepto;
    private javax.swing.JButton btn_modConcepto;
    private javax.swing.JComboBox cbx_tipoConcepto;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JTable tbl_conceptos;
    private javax.swing.JTextField txt_detalleConcepto;
    // End of variables declaration//GEN-END:variables
}
