/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Clases.Foto;
import Clases.ImprimirAuditoria;
import Clases.Maestro;
import Clases.Operario;
import Clases.Remiseria;
import Clases.Utilidad;
import Log_Auditoria.Auditoria_Operacional;
import Log_Auditoria.Entidad_Revisada;
import java.awt.Font;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author garba
 */
public class JDialogAuditoria extends javax.swing.JDialog {
    private Remiseria unaRemiseria;
   // private List<Entidad_Revisada> colador = new LinkedList<>();
    private List<ImprimirAuditoria> colador = new LinkedList<>();
    private List<Auditoria_Operacional> col2 = new LinkedList<>();
    private Utilidad utilidades = new Utilidad();
    private Maestro unMaestro;
    private Operario unOperario;
    /**
     * Creates new form JDialogAuditoria
     */
    public JDialogAuditoria(java.awt.Frame parent, boolean modal, Remiseria unaRemiseria, Maestro unMaestro, Operario unOperario) {
        super(parent, modal);
        this.unaRemiseria = unaRemiseria;
        this.unMaestro = unMaestro;
        this.unOperario = unOperario;
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);
        lbl_desde.setText("");
        lbl_hasta.setText("");
        dp_desdeFecha.setEnabled(false);
        dp_hastaFecha.setEnabled(false);  
        JTableHeader th;
        th = jTable1.getTableHeader(); 
        Font fuente = new Font("Tahoma", Font.BOLD, 12); 
        th.setForeground(java.awt.Color.BLACK);
        th.setBackground(java.awt.Color.white);
        th.setFont(fuente); 
    }

    public static void limpiar_tabla(JTable tabla) {
        int filas = tabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }    
    
    
    public  void cargarTablaAuditoria(JTable tabla, List<ImprimirAuditoria> lista) {
        try
        {
        limpiar_tabla(tabla);
        String[] filas = new String[4];
        Collections.sort(lista, new Comparator<ImprimirAuditoria>() {
                @Override
                public int compare(ImprimirAuditoria p1, ImprimirAuditoria p2) {                
                        return new Long(p1.getMomento().getTime()).compareTo(new Long(p2.getMomento().getTime()));
                }
        });        
       // for (Entidad_Revisada lala : lista) {
        for (ImprimirAuditoria lala : lista) {    
           // filas[0] = String.valueOf(lala.getId());//getCustomTimestamp());
            filas[0] = lala.getAccion();
            filas[1] = lala.getEntityClassName();
            filas[2] = lala.getUsuario();
            filas[3] = utilidades.getFecha(lala.getMomento())+"-"+ utilidades.getHora(lala.getMomento());
            ((DefaultTableModel) tabla.getModel()).addRow(filas);
        }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error al cargar la Tabla de Logs");
        }
    }    
    
    public static void cargarTablaAuditoria2(JTable tabla, List<Auditoria_Operacional> lista) {
        limpiar_tabla(tabla);
        String[] filas = new String[5];
        for (Auditoria_Operacional lala : lista) {
            filas[0] = String.valueOf(lala.getId());//getCustomTimestamp());
            filas[1] = lala.getOperacion();
            filas[2] = lala.getDetalle();
            filas[3] = lala.getUsuarioResponsable();
            filas[4] = lala.getFecha().toString();
            ((DefaultTableModel) tabla.getModel()).addRow(filas);
        }

    }      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_filtrado = new javax.swing.JLabel();
        cbx_accion = new javax.swing.JComboBox();
        dp_desdeFecha = new org.jdesktop.swingx.JXDatePicker();
        lbl_desde = new javax.swing.JLabel();
        dp_hastaFecha = new org.jdesktop.swingx.JXDatePicker();
        lbl_hasta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbx_filtro = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_numero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(117, 150, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Acción Realizada", "Clase Persistida", "Usuario Responsable", "Fecha del Hecho"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton2.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application-exit.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PRINTER 1.png"))); // NOI18N
        jButton1.setText("Listar");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_ver.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/computer.png"))); // NOI18N
        btn_ver.setText("Visualizar");
        btn_ver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel30.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel30.setText("Logs de Auditoria");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(117, 150, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N

        lbl_filtrado.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        lbl_filtrado.setText("Acción Realizada:");

        cbx_accion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbx_accion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agregado", "Modificación", "Eliminación" }));
        cbx_accion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_accionItemStateChanged(evt);
            }
        });

        dp_desdeFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_desde.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        lbl_desde.setText("Desde:");

        dp_hastaFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_hasta.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        lbl_hasta.setText("Hasta:");

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jLabel5.setText("Filtrar por:");

        cbx_filtro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbx_filtro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acción Realizada", "Usuario Particular", "Fecha del Hecho" }));
        cbx_filtro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_filtroItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel6.setText("Opciones de búsqueda:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jLabel4.setText("Total");

        lbl_numero.setBackground(new java.awt.Color(255, 255, 255));
        lbl_numero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_numero.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_filtrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_accion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_hasta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dp_hastaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_desde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dp_desdeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dp_desdeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_desde)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cbx_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dp_hastaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_hasta))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_filtrado)
                                .addComponent(cbx_accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbl_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_accionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_accionItemStateChanged
        int filtro1 = cbx_filtro.getSelectedIndex();
        int filtro2 = cbx_accion.getSelectedIndex();
        if (filtro1 == 2) {
            if (filtro2 == 0) {
                lbl_desde.setText("Seleccione un Día");
                lbl_hasta.setText("");
                dp_desdeFecha.setEnabled(true);
                dp_desdeFecha.setDate(new Date());
                dp_hastaFecha.setEnabled(false);
                dp_hastaFecha.setDate(null);

            } else {
                lbl_desde.setText("A partir de:");
                lbl_hasta.setText("Hasta la fecha:");
                dp_desdeFecha.setEnabled(true);
                dp_desdeFecha.setDate(new Date());
                dp_hastaFecha.setEnabled(true);
                dp_hastaFecha.setDate(new Date());
            }
        } else {
            lbl_desde.setText("");
            lbl_hasta.setText("");
            dp_desdeFecha.setEnabled(false);
            dp_hastaFecha.setEnabled(false);
            dp_desdeFecha.setDate(null);
            dp_hastaFecha.setDate(null);

        }
    }//GEN-LAST:event_cbx_accionItemStateChanged

    
    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed

        colador.clear();
        col2.clear();
        List resultado = Remiseria.persistencia.buscarRevisiones("entidad_revisada");
        List r = unaRemiseria.getAudiciones();
        int filtro = cbx_filtro.getSelectedIndex();
        String accion = null;
        String a = null;
        Date desde = null;
        Date hasta = null;
        switch (filtro) 
        {
            case 0:
            accion = (String) cbx_accion.getSelectedItem();
            switch (accion) {
                case ("Agregado"):
                a = "ADD";
                break;
                case ("Modificación"):
                a = "MOD";
                break;
                case ("Eliminación"):
                a = "DEL";
                break;
                default:
                a = "";
                break;
            }
            break;
            case 1:
            a = (String) cbx_accion.getSelectedItem().toString();
            break;
            case 2:
            accion = (String) cbx_accion.getSelectedItem();
            switch (accion) {
                case ("Día en particular"):
                desde = (dp_desdeFecha.getDate());
                case ("Período"):
                desde = dp_desdeFecha.getDate();
                hasta = dp_hastaFecha.getDate();

            }

        }
//            if(cbx_accion.getSelectedItem().toString().equals("Eliminación"))
//            {   System.out.println(r);
//                for (Iterator iterador = r.iterator(); iterador.hasNext();) {
//                Auditoria_Operacional tupla = (Auditoria_Operacional) iterador.next();
//                if (filtro == 0) {
//                    if (tupla.getOperacion().toUpperCase().equals(a.toUpperCase())) {
//                        col2.add(tupla);
//                    }
//                }
//                if (filtro == 1) {
//                    if (tupla.getUsuarioResponsable()!= null) {
//                        if (tupla.getUsuarioResponsable().equals(a)) {
//                            col2.add(tupla);
//                        }
//                    }
//                }
//
//                if (filtro == 2) {
//                    if (accion.equals("Día en particular")) {
//                        if (utilidades.getDate(utilidades.getFecha(tupla.getFecha())).equals(utilidades.getDate(utilidades.getFecha(desde)))) {
//                            col2.add(tupla);
//                        }
//                    }
//                    if (accion.equals("Período")) {
//                        if ((tupla.getFecha().equals(desde) || tupla.getFecha().after(desde)) && (tupla.getFecha().equals(desde) || tupla.getFecha().before(hasta))) {
//                            col2.add(tupla);
//                        }
//
//                    }
//                }           
//            }
//            cargarTablaAuditoria2(jTable1, col2);
//            lbl_numero.setText(String.valueOf(jTable1.getRowCount()));
//            }
//            else
//            {
       
            for (Iterator iterador = resultado.iterator(); iterador.hasNext();) 
            {
                Entidad_Revisada tupla = (Entidad_Revisada) iterador.next();
                
                if (filtro == 0) {
                    if (tupla.getAccion().toUpperCase().equals(a.toUpperCase())) {
                        colador.add(new ImprimirAuditoria(tupla.getEntityClassName(),tupla.getUsuario(),tupla.getAccion(),tupla.getMomento()));
                    }
                }
                if (filtro == 1) {
                    if (tupla.getUsuario() != null) {
                        if (tupla.getUsuario().equals(a)) {
                            colador.add(new ImprimirAuditoria(tupla.getEntityClassName(),tupla.getUsuario(),tupla.getAccion(),tupla.getMomento()));
                        }
                    }
                }

                if (filtro == 2) {
                    if (accion.equals("Día en particular")) {
                        if (utilidades.getDate(utilidades.getFecha(tupla.getMomento())).equals(utilidades.getDate(utilidades.getFecha(desde)))) {
                            colador.add(new ImprimirAuditoria(tupla.getEntityClassName(),tupla.getUsuario(),tupla.getAccion(),tupla.getMomento()));                        }
                    }
                    if (accion.equals("Período")) {
                        if ((tupla.getMomento().equals(desde) || tupla.getMomento().after(desde)) && (tupla.getMomento().equals(desde) || tupla.getMomento().before(hasta))) {
                            colador.add(new ImprimirAuditoria(tupla.getEntityClassName(),tupla.getUsuario(),tupla.getAccion(),tupla.getMomento()));                        }

                    }
                }
            }
            //Eliminados
            for (Iterator iterador = r.iterator(); iterador.hasNext();) 
            {
                Auditoria_Operacional tupla = (Auditoria_Operacional) iterador.next();
                
                if (filtro == 0) {
                    if (tupla.getOperacion().toUpperCase().equals(a.toUpperCase())) {
                        colador.add(new ImprimirAuditoria(tupla.getDetalle(),tupla.getUsuarioResponsable(),tupla.getOperacion(),tupla.getFecha()));
                    }
                }
                if (filtro == 1) {
                    if (tupla.getUsuarioResponsable() != null) {
                        if (tupla.getUsuarioResponsable().equals(a)) {
                           colador.add(new ImprimirAuditoria(tupla.getDetalle(),tupla.getUsuarioResponsable(),tupla.getOperacion(),tupla.getFecha()));
                        }
                    }
                }

                if (filtro == 2) {
                    if (accion.equals("Día en particular")) {
                        if (utilidades.getDate(utilidades.getFecha(tupla.getFecha())).equals(utilidades.getDate(utilidades.getFecha(desde)))) {
                           colador.add(new ImprimirAuditoria(tupla.getDetalle(),tupla.getUsuarioResponsable(),tupla.getOperacion(),tupla.getFecha()));
                        }
                    }
                    if (accion.equals("Período")) {
                        if ((tupla.getFecha().equals(desde) || tupla.getFecha().after(desde)) && (tupla.getFecha().equals(desde) || tupla.getFecha().before(hasta))) {
                            colador.add(new ImprimirAuditoria(tupla.getDetalle(),tupla.getUsuarioResponsable(),tupla.getOperacion(),tupla.getFecha()));
                        }

                    }
                }
            }            
            cargarTablaAuditoria(jTable1, colador);
            lbl_numero.setText(String.valueOf(jTable1.getRowCount()));
////            }
        
    }//GEN-LAST:event_btn_verActionPerformed

    
    
    private void cbx_filtroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_filtroItemStateChanged
        int filtro = cbx_filtro.getSelectedIndex();
        switch (filtro) {
            case 0:
            lbl_filtrado.setText("Seleccione una Acción");
            cbx_accion.removeAllItems();
           // cbx_accion.addItem("Todos");
            cbx_accion.addItem("Agregado");
            cbx_accion.addItem("Modificación");
            cbx_accion.addItem("Eliminación");
            break;
            case 1:
            lbl_filtrado.setText("Seleccione un Usuario");
            cbx_accion.removeAllItems();
            for (Operario unUsuario : unaRemiseria.getOperarios().values()) {
                cbx_accion.addItem(unUsuario);
            }
            break;
            case 2:
            lbl_filtrado.setText("Seleccione una Fecha");
            cbx_accion.removeAllItems();
            cbx_accion.addItem("Día en particular");
            cbx_accion.addItem("Período");
            break;
        }
    }//GEN-LAST:event_cbx_filtroItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     try {

            HashMap<String, Object> parametros = new HashMap();
            parametros.clear();
                if(unMaestro != null)
                {
                     parametros.put("operario1",unMaestro.getNombre()+" "+unMaestro.getApellido());
                }
                else if(unOperario != null)
                {
                    parametros.put("operario1",unOperario.getNombre()+" "+unOperario.getApellido());
                }
                parametros.put("nombreEmpresa",unaRemiseria.getNombre());
                parametros.put("direccionEmpresa","Calle "+unaRemiseria.getUnDomicilio().getCalle()+" N° "+unaRemiseria.getUnDomicilio().getNroCasa() );
                parametros.put("telefonoEmpresa",unaRemiseria.getUnTelefono().toString());
                parametros.put("fechaActual", utilidades.getFechaActual());
                parametros.put("paisprovincia", unaRemiseria.getUnDomicilio().getUnaCiudad().getNombreCiudad()+"-"+unaRemiseria.getUnDomicilio().getUnaProvincia().getNombreProvincia()+" "+unaRemiseria.getUnDomicilio().getUnPais().getNombrePais());            
                parametros.put ("logo",unaRemiseria.getLogo());
                parametros.put ("total",lbl_numero.getText());
                //C:\Users\garba\Desktop\Reportes
                //JasperReport jasper = JasperCompileManager.compileReport("src/Reportes/Logs.jrxml");
                JasperReport jasper = JasperCompileManager.compileReport("C:/Users/garba/Desktop/Reportes/Logs.jrxml");
                JasperPrint jasperPrint =  null;
                if(colador != null)
                {
                     jasperPrint = JasperFillManager.fillReport(jasper, parametros, new JRBeanCollectionDataSource(colador));
                }
                else
                {
                    jasperPrint = JasperFillManager.fillReport(jasper, parametros, new JRBeanCollectionDataSource(col2));
                }
                JasperViewer jviewer = new JasperViewer(jasperPrint, false);
                JDialog frame;
                frame = new JDialog();
                frame.getContentPane().removeAll();
                frame.getContentPane().add(jviewer.getContentPane());
                frame.pack();
                frame.setSize(1100, 600);
                frame.setModal(true);
                frame.setLocationRelativeTo(null);                  
                frame.show();

            } 
            catch (JRException ex) 
            {
                JOptionPane.showMessageDialog(this, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAuditoria dialog = new JDialogAuditoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ver;
    private javax.swing.JComboBox cbx_accion;
    private javax.swing.JComboBox cbx_filtro;
    private org.jdesktop.swingx.JXDatePicker dp_desdeFecha;
    private org.jdesktop.swingx.JXDatePicker dp_hastaFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_desde;
    private javax.swing.JLabel lbl_filtrado;
    private javax.swing.JLabel lbl_hasta;
    private javax.swing.JLabel lbl_numero;
    // End of variables declaration//GEN-END:variables
}
