/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Clases.Permisos;
import Clases.Remiseria;
import Clases.Rol;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.*;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author garba
 */
public class JDialogRoles extends javax.swing.JDialog {
    
private Remiseria remiseria;
private Rol unRol;
private JComboBox cmbRol;
/**
     * Creates new form JDialogRoles
     */
    public JDialogRoles(java.awt.Frame parent, boolean modal,Remiseria remiseria, JComboBox cmbRol) {
        super(parent, modal);
        this.remiseria = remiseria;
        this.cmbRol = cmbRol;
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);
        cargarInterface();
        JTableHeader th; 
        th = jTable1.getTableHeader(); 
        Font fuente = new Font("Tahoma", Font.BOLD, 12); 
        th.setForeground(java.awt.Color.BLACK);
        th.setBackground(java.awt.Color.white);
        th.setFont(fuente); 
        txt_nombreRol.requestFocus();
    }
       
    public void cargarComboRoles()
    {
        cmbRol.removeAllItems();
        if(remiseria.getRoles()!= null){
            Collection roles = remiseria.getRoles().values();
            Iterator iter = roles.iterator();
            while (iter.hasNext()){
                Rol unRol = (Rol) iter.next();
                cmbRol.addItem(unRol.getNombreRol());
            }
        }
    }

    private void cargarInterface()
    {
        btnEliminarRol.setEnabled(false);
        btnModificarRol.setEnabled(false);
        Guardar.setEnabled(true);
        btnCancelarRol.setEnabled(false);
        if(remiseria.getRoles()!=null)
        {
            cargarTablaRoles(jTable1, remiseria.getRoles().values());
        }
    }
    
    public static void limpiar_tabla(JTable tabla)
    {
        int filas = tabla.getRowCount();
        for (int i = 0; i < filas; i++)
        {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
        
    public static void cargarTablaRoles(JTable tabla, Collection lista)
    {
        limpiar_tabla(tabla);
        Rol aux = null;
        JTableHeader th; 
        th = tabla.getTableHeader(); 
        Font fuente = new Font("Tahoma", Font.BOLD, 12); 
        th.setForeground(java.awt.Color.BLACK);
        th.setBackground(java.awt.Color.white);
        th.setFont(fuente); 
        Iterator iter = lista.iterator();
        while(iter.hasNext())
        {
            aux = (Rol) iter.next();
             ((DefaultTableModel) tabla.getModel()).addRow(aux.toVector());
        }
        
    }
    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Guardar = new javax.swing.JButton();
        btnModificarRol = new javax.swing.JButton();
        btnEliminarRol = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCancelarRol = new javax.swing.JButton();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jLabel1 = new javax.swing.JLabel();
        txt_nombreRol = new javax.swing.JTextField();
        pnl_permisos = new javax.swing.JPanel();
        permitirGestionDeCaja = new javax.swing.JCheckBox();
        permitirGestionDeUsuarios = new javax.swing.JCheckBox();
        permitirGestionDeClientes = new javax.swing.JCheckBox();
        permitirGestionDeChoferes = new javax.swing.JCheckBox();
        permitirGestionDeMoviles = new javax.swing.JCheckBox();
        permitirGestionDeTarifas = new javax.swing.JCheckBox();
        permitirGestionDeZonas = new javax.swing.JCheckBox();
        permitirGestionDeViajes = new javax.swing.JCheckBox();
        permitirGestionDeLogs = new javax.swing.JCheckBox();
        permitirGestionDeRespaldo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Guardar.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/media-floppy.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        btnModificarRol.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btnModificarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accessories-text-editor.png"))); // NOI18N
        btnModificarRol.setText("Modificar");
        btnModificarRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRolActionPerformed(evt);
            }
        });

        btnEliminarRol.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btnEliminarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-trash.png"))); // NOI18N
        btnEliminarRol.setText("Eliminar ");
        btnEliminarRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRolActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application-exit.png"))); // NOI18N
        btnCancelar.setText("Salir");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCancelarRol.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        btnCancelarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gtk-no.png"))); // NOI18N
        btnCancelarRol.setText("Cancelar ");
        btnCancelarRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarRol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarRol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarRol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jXTaskPaneContainer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jLabel1.setText("Nombre del Rol:");

        txt_nombreRol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombreRol.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombreRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nombreRolMouseClicked(evt);
            }
        });
        txt_nombreRol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreRolKeyTyped(evt);
            }
        });

        pnl_permisos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione los Permisos que tendrá el Rol", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Goudy Old Style", 0, 18), java.awt.Color.black)); // NOI18N
        pnl_permisos.setLayout(new java.awt.GridLayout(7, 2));

        permitirGestionDeCaja.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeCaja.setText("Permitir Gestión de Caja");
        permitirGestionDeCaja.setName("permitirGestionDeCaja"); // NOI18N
        pnl_permisos.add(permitirGestionDeCaja);

        permitirGestionDeUsuarios.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeUsuarios.setText("Permitir Gestión de Usuarios");
        permitirGestionDeUsuarios.setName("permitirGestionDeUsuarios"); // NOI18N
        permitirGestionDeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitirGestionDeUsuariosActionPerformed(evt);
            }
        });
        pnl_permisos.add(permitirGestionDeUsuarios);

        permitirGestionDeClientes.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeClientes.setText("Permitir Gestión de Clientes");
        permitirGestionDeClientes.setName("permitirGestionDeClientes"); // NOI18N
        pnl_permisos.add(permitirGestionDeClientes);

        permitirGestionDeChoferes.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeChoferes.setText("Permitir Gestión de Choferes");
        permitirGestionDeChoferes.setName("permitirGestionDeChoferes"); // NOI18N
        pnl_permisos.add(permitirGestionDeChoferes);

        permitirGestionDeMoviles.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeMoviles.setText("Permitir Gestión de Móviles");
        permitirGestionDeMoviles.setName("permitirGestionDeMoviles"); // NOI18N
        pnl_permisos.add(permitirGestionDeMoviles);

        permitirGestionDeTarifas.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeTarifas.setText("Permitir Gestión de Tarifas");
        permitirGestionDeTarifas.setName("permitirGestionDeTarifas"); // NOI18N
        pnl_permisos.add(permitirGestionDeTarifas);

        permitirGestionDeZonas.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeZonas.setText("Permitir Gestión de Zonas");
        permitirGestionDeZonas.setName("permitirGestionDeZonas"); // NOI18N
        pnl_permisos.add(permitirGestionDeZonas);

        permitirGestionDeViajes.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeViajes.setText("Permitir Gestión de Viajes");
        permitirGestionDeViajes.setName("permitirGestionDeViajes"); // NOI18N
        pnl_permisos.add(permitirGestionDeViajes);

        permitirGestionDeLogs.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeLogs.setText("Permitir Logs de Auditoria");
        permitirGestionDeLogs.setName("permitirGestionDeLogs"); // NOI18N
        pnl_permisos.add(permitirGestionDeLogs);

        permitirGestionDeRespaldo.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        permitirGestionDeRespaldo.setText("Permitir Respaldos");
        permitirGestionDeRespaldo.setName("permitirGestionDeRespaldo"); // NOI18N
        pnl_permisos.add(permitirGestionDeRespaldo);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jXTaskPaneContainer1Layout = new javax.swing.GroupLayout(jXTaskPaneContainer1);
        jXTaskPaneContainer1.setLayout(jXTaskPaneContainer1Layout);
        jXTaskPaneContainer1Layout.setHorizontalGroup(
            jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTaskPaneContainer1Layout.createSequentialGroup()
                .addGroup(jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTaskPaneContainer1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTaskPaneContainer1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_permisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nombreRol))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jXTaskPaneContainer1Layout.setVerticalGroup(
            jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTaskPaneContainer1Layout.createSequentialGroup()
                .addGroup(jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombreRol, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(pnl_permisos, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel2.setText("Gestor de Roles");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(576, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Rol rolSeleccionado;
        if (jTable1.getRowCount() > 0)
        {
            rolSeleccionado = remiseria.buscarUnRol(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0))) ;
            txt_nombreRol.setText(rolSeleccionado.getNombreRol().toString());
            for (Component unComponent : pnl_permisos.getComponents())
            {
                ((JCheckBox) unComponent).setSelected(false);
            }  
            Permisos aux = null;
            Collection permisos = rolSeleccionado.getPermisos().values();
            Iterator it = permisos.iterator();
            while (it.hasNext())
            {
                aux = (Permisos)it.next();
                for (Component unComponent : pnl_permisos.getComponents())
                {
                    if(aux.getTipo().equals(unComponent.getName()))
                    {
                         ((JCheckBox) unComponent).setSelected(true);
                         break;
                    }
                }
            }

            }
        else 
        {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error en la seleccion del Rol");
        }
        Guardar.setEnabled(false);
        btnModificarRol.setEnabled(true);
        btnEliminarRol.setEnabled(true);
        btnCancelarRol.setEnabled(true);  
    }//GEN-LAST:event_jTable1MouseClicked

    private void permitirGestionDeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitirGestionDeUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permitirGestionDeUsuariosActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String nombre;
        Map<String, Permisos> permisos = new HashMap<>();
        permisos.clear();
        for (Component unComponent : pnl_permisos.getComponents())
        {
            if (unComponent instanceof JCheckBox) 
            {
                if (((JCheckBox) unComponent).isSelected())
                {
                    Permisos nuevoPermiso = new Permisos(unComponent.getName());
                    permisos.put(nuevoPermiso.getTipo(), nuevoPermiso);
                }
            }
        }     
        
        if (!txt_nombreRol.getText().isEmpty())
        {
            nombre = txt_nombreRol.getText();
            if (!permisos.isEmpty())
            {
                try
                {
                    remiseria.agregarRol(nombre, permisos);
                    this.cargarComboRoles();
                    JOptionPane.showMessageDialog(this, "Se ha registrado un nuevo Rol");
                }
                catch (Exception ex)
                {
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
            else 
            {
                JOptionPane.showMessageDialog(this, "Debe al menos seleccionar un Permiso para crear el nuevo Rol");
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "Debe Ingresar un Nombre al nuevo Rol");
            txt_nombreRol.setBackground(Color.red);
        }
        cargarInterface();
    }//GEN-LAST:event_GuardarActionPerformed

    private void btnModificarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRolActionPerformed
        // TODO add your handling code here:
        String nombre;
        unRol =   remiseria.buscarUnRol(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0))); 
        Map<String, Permisos> permisos;
        permisos = new HashMap<>();
        permisos.clear();
        for (Component unComponent : pnl_permisos.getComponents()) 
        {
            if (unComponent instanceof JCheckBox) 
            {
                if (((JCheckBox) unComponent).isSelected())
                {
                    Permisos nuevoPermiso = new Permisos(unComponent.getName());
                    permisos.put(nuevoPermiso.getTipo(), nuevoPermiso);
                }
            }
        }
        if (!txt_nombreRol.getText().isEmpty())
        {
            nombre = txt_nombreRol.getText();
            if (!permisos.isEmpty()) 
            {
                try 
                {
                    remiseria.modificarRol(unRol, nombre, permisos);
                    
                } 
                catch (Exception ex)
                {
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(this, ex);
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(null,"Debe al menos un Permiso para crear el nuevo Rol"," ",JOptionPane.ERROR_MESSAGE);
               
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"Debe Ingresar un Nombre al nuevo Rol"," ",JOptionPane.ERROR_MESSAGE);
        }
        cargarInterface();
    }//GEN-LAST:event_btnModificarRolActionPerformed

    private void btnEliminarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRolActionPerformed
        // TODO add your handling code here:
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar el Rol seleccionado?");
        if ( eleccion == 0)
        {
            Rol rolseleccionado =   remiseria.buscarUnRol(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
            if (rolseleccionado != null) 
            {
                try 
                {              
                    rolseleccionado.EliminarUnPermiso(rolseleccionado,remiseria);
                    remiseria.eliminarRol(rolseleccionado);
                    cargarInterface();
                } 
                catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex);
                    System.out.println(ex);
                }
            } 
            else
            {
                JOptionPane.showMessageDialog(this, "Debe seleccionar algun rol antes de continuar");
            }
        }
    }//GEN-LAST:event_btnEliminarRolActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRolActionPerformed
        // TODO add your handling code here:
        for (Component unComponent : pnl_permisos.getComponents())
        {
                ((JCheckBox) unComponent).setSelected(false);
        }
        btnEliminarRol.setEnabled(false);
        btnModificarRol.setEnabled(false);
        btnCancelarRol.setEnabled(false);
        Guardar.setEnabled(true);
        txt_nombreRol.setText("");
    }//GEN-LAST:event_btnCancelarRolActionPerformed

    private void txt_nombreRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreRolMouseClicked
        // TODO add your handling code here:
        txt_nombreRol.setBackground(Color.white);
    }//GEN-LAST:event_txt_nombreRolMouseClicked

    private void txt_nombreRolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreRolKeyTyped
        // TODO add your handling code here:
        int limite  = 15;
        {if (txt_nombreRol.getText().length()== limite)
            evt.consume();
        }               
    }//GEN-LAST:event_txt_nombreRolKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
     
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogRoles dialog = new JDialogRoles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });    */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarRol;
    private javax.swing.JButton btnEliminarRol;
    private javax.swing.JButton btnModificarRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private javax.swing.JCheckBox permitirGestionDeCaja;
    private javax.swing.JCheckBox permitirGestionDeChoferes;
    private javax.swing.JCheckBox permitirGestionDeClientes;
    private javax.swing.JCheckBox permitirGestionDeLogs;
    private javax.swing.JCheckBox permitirGestionDeMoviles;
    private javax.swing.JCheckBox permitirGestionDeRespaldo;
    private javax.swing.JCheckBox permitirGestionDeTarifas;
    private javax.swing.JCheckBox permitirGestionDeUsuarios;
    private javax.swing.JCheckBox permitirGestionDeViajes;
    private javax.swing.JCheckBox permitirGestionDeZonas;
    private javax.swing.JPanel pnl_permisos;
    private javax.swing.JTextField txt_nombreRol;
    // End of variables declaration//GEN-END:variables
}
